name: flutter_cast_framework_example
description: Demonstrates how to use the flutter_cast_framework plugin.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0

  flutter_cast_framework:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
