name: flutter_cast_framework
description: A plugin to interact with Chromecast.
version: 0.0.1-alpha.1
homepage: https://github.com/gianlucaparadise/flutter_cast_framework
documentation: https://gianlucaparadise.github.io/flutter_cast_framework/api/

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gianlucaparadise.flutter_cast_framework
        pluginClass: FlutterCastFrameworkPlugin
      ios:
        pluginClass: FlutterCastFrameworkPlugin

  uses-material-design: true
