name: flutter_cast_framework
description: A plugin to interact with Chromecast.
version: 0.0.1-alpha.1
homepage: https://github.com/gianlucaparadise/flutter_cast_framework
documentation: https://gianlucaparadise.github.io/flutter_cast_framework/api/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^21.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The package and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.gianlucaparadise.flutter_cast_framework
        pluginClass: FlutterCastFrameworkPlugin
      ios:
        pluginClass: FlutterCastFrameworkPlugin

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
